Noetic devel simulation fix missing deps
tahsinkose/panda_moveit_config pull request #2
Opened 2021-04-30 14:24 UTC by rickstaa

This pull request adds several missing dependencies which are needed to follow along with the Moveit gazebo tutorial. I am aware that the moveit-simple-controller-manager pkg is already installed when installing moveit is installed but I think marking it as an explicit dependency is more clear.

2021-05-05 10:54 UTC, tahsinkose commented
@rickstaa thanks for the contribution. Please rebase your branch and squeeze the dependency commits into 1 commit :pray:

2021-05-05 10:57 UTC, tahsinkose requested changes
@rickstaa thanks for the contribution. Please rebase your branch and squeeze the dependency commits into 1 commit :pray:

2021-05-05 11:10 UTC, rickstaa commented
@tahsinkose I merged  oth commits into one sorry for the clutter. Was that what you had in mind?

2021-05-05 11:12 UTC, tahsinkose commented
Yes. In addition to that you should rebase your branch to latest tip of `tahsinkose:melodic-devel` so that only your commit will be listed in PR.

2021-05-05 11:21 UTC, rickstaa commented
Closed by #4

2021-05-05 11:23 UTC, rickstaa commented
Sorry closed wrong one

2021-05-05 11:24 UTC, rickstaa commented
Replaced with #4

2021-05-06 19:53 UTC, tahsinkose commented on package.xml
> +  <run_depend>rqt_joint_trajectory_controller</run_depend>
This one is not an actual dependency of panda_moveit_config.

2021-05-06 20:06 UTC, rickstaa commented on package.xml
> +  <run_depend>rqt_joint_trajectory_controller</run_depend>
@tahsinkose Correct. The only reason I added is that it is needed to successfully complete [the tutorial](https://ros-planning.github.io/moveit_tutorials/doc/gazebo_simulation/gazebo_simulation.html?highlight=gazebo).

2021-05-06 20:09 UTC, tahsinkose commented on package.xml
> +  <run_depend>rqt_joint_trajectory_controller</run_depend>
I see that. However we must rely upon bare minimum ROS knowledge from people to install that themselves if that package is missing :slightly_smiling_face: AFAIU, this package is not just being used for tutorial purposes, but also used for production.

2021-05-06 20:10 UTC, tahsinkose commented
@rickstaa you don't need to reopen it. I already cherry-picked it to base branch :+1: See https://github.com/tahsinkose/panda_moveit_config/commit/ac4cec548a25a1b3da2202706bc6479681cf302c

2021-05-06 20:12 UTC, closed without merging

2021-05-06 20:13 UTC, rickstaa commented on package.xml
> +  <run_depend>rqt_joint_trajectory_controller</run_depend>
@tahsinkose Ah thanks for the tip!